version: '3.0'
services:
   db:
      image: "postgres"
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
        POSTGERS_DB: MyCompany
      ports:
        - "5432:5432"
      restart: unless-stopped
      volumes:
        - database-data:/var/lib/postgresql/data        
   mycompany:
     depends_on:
       - db
     image: ivan/mycompany:runtime
     build:
       context: .
     ports:
       - "8080:5000"
       - "8081:5001"
     environment:
       - ASPNETCORE_Kestrel__Certificates__Default__Password=awesomepass
       - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/mycompany.pfx
       - SECRET=mycompanySecretKey
     volumes: 
       - ${USERPROFILE}/.aspnet/https:/https/ 
volumes:
  database-data:
   
